from attrs import field, frozen
from datetime import datetime
from metafold.api import asdatetime, asdict, optional, optional_datetime
from metafold.assets import Asset
from metafold.client import Client
from metafold.exceptions import PollTimeout
from requests import Response
from typing import Any, TypeAlias, TypedDict


def _assets(v: list[dict[str, Any] | Asset]) -> list[Asset]:
    return [a if isinstance(a, Asset) else Asset(**a) for a in v]


AssetDict: TypeAlias = dict[str, dict[str, Any] | Asset]


def _assets_dict(v: AssetDict) -> dict[str, Asset]:
    return dict(
        (k, a if isinstance(a, Asset) else Asset(**a))
        for k, a in v.items()
    )


class IODict(TypedDict):
    params: dict[str, Any] | None
    assets: dict[str, AssetDict] | None


@frozen(kw_only=True)
class IO:
    """Job input/output.

    Attributes:
        params: JSON-encoded parameter values.
        assets: Related assets.
    """
    params: dict[str, Any] | None = None
    assets: dict[str, Asset] | None = field(
        converter=lambda v: optional(_assets_dict)(v), default=None)

    @staticmethod
    def from_dict(d: IODict) -> "IO":
        return IO(params=d.get("params"), assets=d.get("assets"))


@frozen(kw_only=True)
class Job:
    """Job resource.

    Attributes:
        id: Job ID.
        name: Job name.
        type: Job type.
        state: Job state. May be one of: pending, started, success, failure, or
            canceled.
        created: Job creation datetime.
        started: Job started datetime.
        finished: Job finished datetime.
        error: Error message for failed jobs.
        inputs: Input assets and parameters.
        outputs: Output assets and parameters.
        needs: List of upstream job IDs in a workflow graph.
        project_id: Project ID.
        workflow_id: Workflow ID.
        assets: (Deprecated) List of generated asset resources.
        parameters: (Deprecated) Job parameters.
        meta: (Deprecated) Additional metadata generated by the job.
    """
    id: str
    name: str | None = None
    type: str
    state: str
    created: datetime = field(converter=asdatetime)
    started: datetime | None = field(
        converter=lambda v: optional_datetime(v), default=None)
    finished: datetime | None = field(
        converter=lambda v: optional_datetime(v), default=None)
    error: str | None = None
    inputs: IO = field(converter=lambda v: v if isinstance(v, IO) else IO.from_dict(v))
    outputs: IO = field(converter=lambda v: v if isinstance(v, IO) else IO.from_dict(v))
    needs: list[str]
    project_id: str | None = None
    workflow_id: str | None = None
    # NOTE(ryan): Deprecated
    assets: list[Asset] | None = field(
        converter=lambda v: optional(_assets)(v), default=None)
    parameters: dict[str, Any]
    meta: dict[str, Any]


class JobsEndpoint:
    """Metafold jobs endpoint."""

    def __init__(self, client: Client) -> None:
        self._client = client

    def list(
        self,
        sort: str | None = None,
        q: str | None = None,
        project_id: str | None = None,
    ) -> list[Job]:
        """List jobs.

        Args:
            sort: Sort string. For details on syntax see the Metafold API docs.
                Supported sorting fields are: "id", "name", "created", "started", or
                "finished".
            q: Query string. For details on syntax see the Metafold API docs.
                Supported search fields are: "id", "name", "type", and "state".
            project_id: Job project ID.

        Returns:
            List of job resources.
        """
        project_id = self._client.project_id(project_id)
        url = f"/projects/{project_id}/jobs"
        payload = asdict(sort=sort, q=q)
        r: Response = self._client.get(url, params=payload)
        return [Job(**j) for j in r.json()]

    def get(self, job_id: str, project_id: str | None = None) -> Job:
        """Get a job.

        Args:
            job_id: ID of job to get.
            project_id: Job project ID.

        Returns:
            Job resource.
        """
        project_id = self._client.project_id(project_id)
        url = f"/projects/{project_id}/jobs/{job_id}"
        r: Response = self._client.get(url)
        return Job(**r.json())

    def delete(self, job_id: str, project_id: str | None = None):
        """Delete a job.

        Args:
            job_id: ID of job to delete.
            project_id: Job project ID.
        """
        project_id = self._client.project_id(project_id)
        url = f"/projects/{project_id}/jobs/{job_id}"
        self._client.delete(url)
