---
stages:
- test

default:
  image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
  before_script:
  - uv sync --extra simulation

lint:
  stage: test
  script:
  - uvx ruff check --output-format gitlab . > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

type check:
  stage: test
  script:
  - uv run --locked mypy ./metafold

test:
  stage: test
  script:
  - uv run --locked pytest --junitxml=pytest.xml ./tests
  artifacts:
    when: always
    paths:
    - pytest.xml
    reports:
      junit: pytest.xml
...
