---
name: Python publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          # Use latest stable version
          python-version: "3.x"
      - name: Install build dependencies
        run: python -m pip install --upgrade pip build
      - name: Build package
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: release
      url: https://pypi.org/p/metafold
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/
      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
...
