---
name: Python docs

on:
  workflow_run:
    workflows: ["Python package"]
    types: [completed]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.26"
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync --locked
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          path: _build/html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
...
